update for *tables
Signed-off-by: Ishimoto Shinobu <nagakamira@gmail.com>

diff --git a/stuff/iptables/iptables-flush b/stuff/iptables/iptables-flush
--- a/stuff/iptables/iptables-flush
+++ b/stuff/iptables/iptables-flush
@@ -1,21 +1,18 @@
-#!/bin/sh
-# Usage: iptables-flush [-6]
+#!/bin/bash
+#
+# Usage: iptables-flush [6]
+#
 
-iptables=/usr/bin/iptables
-tables="filter mangle raw"
-
-if [ "$1" = "-6" ]; then
-	iptables=/usr/bin/ip6tables
-else
-  # Only ipv4 has a nat table
-	tables="$tables nat"
+iptables=ip$1tables
+if ! type -p "$iptables" &>/dev/null; then
+  echo "error: invalid argument"
+  exit 1
 fi
 
-for table in ${tables}; do
-	$iptables -t "$table" -F
-	$iptables -t "$table" -X
-done
+while read -r table; do
+  tables+=("/usr/share/iptables/empty-$table.rules")
+done <"/proc/net/ip$1_tables_names"
 
-for chain in INPUT FORWARD OUTPUT; do
-	$iptables -P "$chain" ACCEPT
-done
+if (( ${#tables[*]} )); then
+  cat "${tables[@]}" | "$iptables-restore"
+fi
