dracut
Signed-off-by: Ishimoto Shinobu <nagakamira@gmail.com>

diff --git a/stuff/dracut/0001-POSIX-userland.patch b/stuff/dracut/0001-POSIX-userland.patch
--- a/stuff/dracut/0001-POSIX-userland.patch
+++ b/stuff/dracut/0001-POSIX-userland.patch
@@ -1,18 +1,20 @@
-From 4c914b392927b55b966e2172d6f235d01c062ae1 Mon Sep 17 00:00:00 2001
+From 7a9e7696588f16f862bbeb14886252be4ef784db Mon Sep 17 00:00:00 2001
 From: Ishimoto Shinobu <nagakamira@gmail.com>
-Date: Mon, 27 Jul 2020 15:01:39 +0300
-Subject: [PATCH] suckless
+Date: Mon, 31 Aug 2020 17:02:00 +0900
+Subject: [PATCH] POSIX userland
 
 Signed-off-by: Ishimoto Shinobu <nagakamira@gmail.com>
 ---
  50-dracut.install                    |  2 +-
  51-dracut-rescue-postinst.sh         |  2 +-
  51-dracut-rescue.install             |  2 +-
- Makefile                             |  6 ++---
- dracut-init.sh                       | 12 +++++-----
- dracut.sh                            | 36 ++++++++++++++--------------
- install/dracut-install.c             |  8 +++----
+ Makefile                             |  2 +-
+ dracut-init.sh                       | 28 ++++++++++--------------
+ dracut.conf                          |  4 ++++
+ dracut.sh                            | 32 ++++++++++++++--------------
+ install/dracut-install.c             |  4 ++--
  modules.d/04watchdog/module-setup.sh |  4 ++--
+ modules.d/30convertfs/convertfs.sh   |  4 ++--
  modules.d/40network/net-lib.sh       |  2 +-
  modules.d/45ifcfg/write-ifcfg.sh     |  2 +-
  modules.d/90crypt/cryptroot-ask.sh   |  4 ++--
@@ -20,12 +22,13 @@ Signed-off-by: Ishimoto Shinobu <nagakamira@gmail.com>
  modules.d/95iscsi/module-setup.sh    |  2 +-
  modules.d/99base/dracut-lib.sh       |  2 +-
  modules.d/99base/init.sh             |  2 +-
+ modules.d/99base/module-setup.sh     |  2 +-
  test/TEST-12-RAID-DEG/test.sh        |  4 ++--
  test/TEST-99-RPM/test.sh             |  2 +-
- 17 files changed, 47 insertions(+), 47 deletions(-)
+ 20 files changed, 53 insertions(+), 55 deletions(-)
 
 diff --git a/50-dracut.install b/50-dracut.install
-index 7ea5e17..81bb765 100755
+index 7ea5e17..3112d9e 100755
 --- a/50-dracut.install
 +++ b/50-dracut.install
 @@ -25,7 +25,7 @@ case "$COMMAND" in
@@ -33,12 +36,12 @@ index 7ea5e17..81bb765 100755
              # we found an initrd at the same place as the kernel
              # use this and don't generate a new one
 -            cp --reflink=auto "$INITRD_IMAGE_PREGENERATED" "$BOOT_DIR_ABS/$INITRD" \
-+            cp  "$INITRD_IMAGE_PREGENERATED" "$BOOT_DIR_ABS/$INITRD" \
++            cp "$INITRD_IMAGE_PREGENERATED" "$BOOT_DIR_ABS/$INITRD" \
                  && chown root:root "$BOOT_DIR_ABS/$INITRD" \
                  && chmod 0600 "$BOOT_DIR_ABS/$INITRD" \
                  && exit 0
 diff --git a/51-dracut-rescue-postinst.sh b/51-dracut-rescue-postinst.sh
-index 67f5b71..8b92e41 100755
+index 67f5b71..2315855 100755
 --- a/51-dracut-rescue-postinst.sh
 +++ b/51-dracut-rescue-postinst.sh
 @@ -57,7 +57,7 @@ if [[ ! -f $INITRDFILE ]]; then
@@ -46,12 +49,12 @@ index 67f5b71..8b92e41 100755
  
  if [[ ! -f $NEW_KERNEL_IMAGE ]]; then
 -    cp --reflink=auto "$KERNEL_IMAGE" "$NEW_KERNEL_IMAGE"
-+    cp  "$KERNEL_IMAGE" "$NEW_KERNEL_IMAGE"
++    cp "$KERNEL_IMAGE" "$NEW_KERNEL_IMAGE"
      ((ret+=$?))
  fi
  
 diff --git a/51-dracut-rescue.install b/51-dracut-rescue.install
-index b4ed178..68c8037 100755
+index b4ed178..d3747ec 100755
 --- a/51-dracut-rescue.install
 +++ b/51-dracut-rescue.install
 @@ -87,7 +87,7 @@ case "$COMMAND" in
@@ -59,43 +62,25 @@ index b4ed178..68c8037 100755
          [[ -d "$BOOT_DIR_ABS" ]] || mkdir -p "$BOOT_DIR_ABS"
  
 -        if ! cp --reflink=auto "$KERNEL_IMAGE" "$BOOT_DIR_ABS/$KERNEL"; then
-+        if ! cp  "$KERNEL_IMAGE" "$BOOT_DIR_ABS/$KERNEL"; then
++        if ! cp "$KERNEL_IMAGE" "$BOOT_DIR_ABS/$KERNEL"; then
              echo "Can't copy '$KERNEL_IMAGE to '$BOOT_DIR_ABS/$KERNEL'!" >&2
          fi
  
 diff --git a/Makefile b/Makefile
-index da56cac..9e092f9 100644
+index 22b584f..7e78bde 100644
 --- a/Makefile
 +++ b/Makefile
-@@ -139,7 +139,7 @@ install: all
- 	ln -fs dracut-functions.sh $(DESTDIR)$(pkglibdir)/dracut-functions
- 	install -m 0755 dracut-logger.sh $(DESTDIR)$(pkglibdir)/dracut-logger.sh
- 	install -m 0755 dracut-initramfs-restore.sh $(DESTDIR)$(pkglibdir)/dracut-initramfs-restore
--	cp -arx modules.d $(DESTDIR)$(pkglibdir)
-+	cp -ar modules.d $(DESTDIR)$(pkglibdir)
- ifneq ($(enable_documentation),no)
- 	for i in $(man1pages); do install -m 0644 $$i $(DESTDIR)$(mandir)/man1/$${i##*/}; done
- 	for i in $(man5pages); do install -m 0644 $$i $(DESTDIR)$(mandir)/man5/$${i##*/}; done
-@@ -149,7 +149,7 @@ ifneq ($(enable_documentation),no)
- endif
- 	if [ -n "$(systemdsystemunitdir)" ]; then \
- 		mkdir -p $(DESTDIR)$(systemdsystemunitdir); \
--		ln -srf $(DESTDIR)$(pkglibdir)/modules.d/98dracut-systemd/dracut-shutdown.service $(DESTDIR)$(systemdsystemunitdir)/dracut-shutdown.service; \
-+		ln -sf $(DESTDIR)$(pkglibdir)/modules.d/98dracut-systemd/dracut-shutdown.service $(DESTDIR)$(systemdsystemunitdir)/dracut-shutdown.service; \
- 		mkdir -p $(DESTDIR)$(systemdsystemunitdir)/sysinit.target.wants; \
- 		ln -s ../dracut-shutdown.service \
- 		$(DESTDIR)$(systemdsystemunitdir)/sysinit.target.wants/dracut-shutdown.service; \
-@@ -163,7 +163,7 @@ endif
+@@ -160,7 +160,7 @@ endif
  		    dracut-pre-trigger.service \
  		    dracut-pre-udev.service \
  		    ; do \
 -			ln -srf $(DESTDIR)$(pkglibdir)/modules.d/98dracut-systemd/$$i $(DESTDIR)$(systemdsystemunitdir); \
-+			ln -sf $(DESTDIR)$(pkglibdir)/modules.d/98dracut-systemd/$$i $(DESTDIR)$(systemdsystemunitdir); \
++			ln -sf $(pkglibdir)/modules.d/98dracut-systemd/$$i $(DESTDIR)$(systemdsystemunitdir); \
  			ln -s ../$$i \
  			$(DESTDIR)$(systemdsystemunitdir)/initrd.target.wants/$$i; \
  		done \
 diff --git a/dracut-init.sh b/dracut-init.sh
-index a8348b7..6dfd8c3 100644
+index a8348b7..583ac76 100644
 --- a/dracut-init.sh
 +++ b/dracut-init.sh
 @@ -20,9 +20,9 @@
@@ -103,10 +88,10 @@ index a8348b7..6dfd8c3 100644
  
  if [[ "$EUID" = "0" ]] && ! [[ $DRACUT_NO_XATTR ]]; then
 -    export DRACUT_CP="cp --reflink=auto --sparse=auto --preserve=mode,timestamps,xattr,links -dfr"
-+    export DRACUT_CP="cp  --sparse=auto --preserve=mode,timestamps,xattr,links -dfr"
++    export DRACUT_CP="cp -f"
  else
 -    export DRACUT_CP="cp --reflink=auto --sparse=auto --preserve=mode,timestamps,links -dfr"
-+    export DRACUT_CP="cp  --sparse=auto --preserve=mode,timestamps,links -dfr"
++    export DRACUT_CP="cp -f"
  fi
  
  # is_func <command>
@@ -135,17 +120,45 @@ index a8348b7..6dfd8c3 100644
      done
  
      echo "${links}"
-@@ -1007,7 +1007,7 @@ else
-     ln_r() {
-         local _source=$1
-         local _dest=$2
+@@ -999,18 +999,12 @@ instmods() {
+     return $_ret
+ }
+ 
+-if [[ "$(ln --help)" == *--relative* ]]; then
+-    ln_r() {
+-        ln -sfnr "${initdir}/$1" "${initdir}/$2"
+-    }
+-else
+-    ln_r() {
+-        local _source=$1
+-        local _dest=$2
 -        [[ -d "${_dest%/*}" ]] && _dest=$(readlink -f "${_dest%/*}")/${_dest##*/}
-+        [[ -d "${_dest%/*}" ]] && _dest=$(realpath "${_dest%/*}")/${_dest##*/}
-         ln -sfn -- "$(convert_abs_rel "${_dest}" "${_source}")" "${initdir}/${_dest}"
-     }
- fi
+-        ln -sfn -- "$(convert_abs_rel "${_dest}" "${_source}")" "${initdir}/${_dest}"
+-    }
+-fi
++ln_r() {
++    local _source=$1
++    local _dest=$2
++    [[ -d "${_dest%/*}" ]] && _dest=$(realpath "${_dest%/*}")/${_dest##*/}
++    ln -sfn -- "$(convert_abs_rel "${_dest}" "${_source}")" "${initdir}/${_dest}"
++}
+ 
+ is_qemu_virtualized() {
+     # 0 if a virt environment was detected
+diff --git a/dracut.conf b/dracut.conf
+index d6317a0..f492e1c 100644
+--- a/dracut.conf
++++ b/dracut.conf
+@@ -1,3 +1,7 @@
+ # PUT YOUR CONFIG IN separate files
+ # in /etc/dracut.conf.d named "<name>.conf"
+ # SEE man dracut.conf(5) for options
++add_dracutmodules+="mksh"
++omit_dracutmodules+="bash i18n"
++i18n_install_all="no"
++compress="zstd"
 diff --git a/dracut.sh b/dracut.sh
-index af346f3..5a360f0 100755
+index af346f3..d8ddcb5 100755
 --- a/dracut.sh
 +++ b/dracut.sh
 @@ -32,7 +32,7 @@ if (( BASH_VERSINFO[0] < 4 )); then
@@ -186,15 +199,6 @@ index af346f3..5a360f0 100755
      fi
      if [[ "$NPATH" != *:$rl* ]] ; then
          NPATH+=":$rl"
-@@ -942,7 +942,7 @@ case "${drivers_dir}" in
- 	;;
- esac
- 
--readonly TMPDIR="$(realpath -e "$tmpdir")"
-+readonly TMPDIR="$(realpath "$tmpdir")"
- [ -d "$TMPDIR" ] || {
-     printf "%s\n" "dracut: Invalid tmpdir '$tmpdir'." >&2
-     exit 1
 @@ -1064,7 +1064,7 @@ case $dracutmodules in
      ""|auto) dracutmodules="all" ;;
  esac
@@ -267,21 +271,12 @@ index af346f3..5a360f0 100755
          push_host_devs "$dev"
          _get_fs_type "$dev"
          check_block_and_slaves_all _get_fs_type "$(get_maj_min "$dev")"
-@@ -1931,7 +1931,7 @@ fi
- if [[ $do_strip = yes ]] && ! [[ $DRACUT_FIPS_MODE ]]; then
-     dinfo "*** Stripping files ***"
-     find "$initdir" -type f \
--        -executable -not -path '*/lib/modules/*.ko' -print0 \
-+        -not -path '*/lib/modules/*.ko' -print0 \
-         | xargs -r -0 $strip_cmd -g -p 2>/dev/null
- 
-     # strip kernel modules, but do not touch signed modules
 @@ -2054,7 +2054,7 @@ if [[ $uefi = yes ]]; then
                  exit 1
              fi
          else
 -            if cp --reflink=auto "${uefi_outdir}/linux.efi" "$outfile"; then
-+            if cp  "${uefi_outdir}/linux.efi" "$outfile"; then
++            if cp "${uefi_outdir}/linux.efi" "$outfile"; then
                  dinfo "*** Creating UEFI image file '$outfile' done ***"
              fi
          fi
@@ -290,37 +285,24 @@ index af346f3..5a360f0 100755
      fi
  else
 -    if cp --reflink=auto "${DRACUT_TMPDIR}/initramfs.img" "$outfile"; then
-+    if cp  "${DRACUT_TMPDIR}/initramfs.img" "$outfile"; then
++    if cp "${DRACUT_TMPDIR}/initramfs.img" "$outfile"; then
          dinfo "*** Creating initramfs image file '$outfile' done ***"
      else
          rm -f -- "$outfile"
 diff --git a/install/dracut-install.c b/install/dracut-install.c
-index 1ba7a82..f0ecab8 100644
+index 3d64ed7..e58e410 100644
 --- a/install/dracut-install.c
 +++ b/install/dracut-install.c
-@@ -312,10 +312,10 @@ static int cp(const char *src, const char *dst)
-         pid = fork();
-         if (pid == 0) {
-                 if (geteuid() == 0 && no_xattr == false)
--                        execlp("cp", "cp", "--reflink=auto", "--sparse=auto", "--preserve=mode,xattr,timestamps", "-fL", src, dst,
-+                        execlp("cp", "cp", "", "--sparse=auto", "--preserve=mode,xattr,timestamps", "-fL", src, dst,
-                                NULL);
-                 else
--                        execlp("cp", "cp", "--reflink=auto", "--sparse=auto", "--preserve=mode,timestamps", "-fL", src, dst,
-+                        execlp("cp", "cp", "", "--sparse=auto", "--preserve=mode,timestamps", "-fL", src, dst,
-                                NULL);
-                 _exit(EXIT_FAILURE);
-         }
 @@ -324,10 +324,10 @@ static int cp(const char *src, const char *dst)
                  if (errno != EINTR) {
                          ret = -1;
                          if (geteuid() == 0 && no_xattr == false)
 -                                log_error("Failed: cp --reflink=auto --sparse=auto --preserve=mode,xattr,timestamps -fL %s %s", src,
-+                                log_error("Failed: cp  --sparse=auto --preserve=mode,xattr,timestamps -fL %s %s", src,
++                                log_error("Failed: cp --sparse=auto --preserve=mode,xattr,timestamps -fL %s %s", src,
                                            dst);
                          else
 -                                log_error("Failed: cp --reflink=auto --sparse=auto --preserve=mode,timestamps -fL %s %s", src,
-+                                log_error("Failed: cp  --sparse=auto --preserve=mode,timestamps -fL %s %s", src,
++                                log_error("Failed: cp --sparse=auto --preserve=mode,timestamps -fL %s %s", src,
                                            dst);
                          break;
                  }
@@ -340,6 +322,24 @@ index 7566d65..61c5cb7 100755
              [[ -f "$_wdtppath/modalias" ]] || continue
  
              _wdtdrv=$(< "$_wdtppath/modalias")
+diff --git a/modules.d/30convertfs/convertfs.sh b/modules.d/30convertfs/convertfs.sh
+index 66bb4a6..aa8c660 100755
+--- a/modules.d/30convertfs/convertfs.sh
++++ b/modules.d/30convertfs/convertfs.sh
+@@ -129,11 +129,11 @@ for dir in bin sbin lib lib64; do
+     [[ -d "$ROOT/$dir" ]] || continue
+     echo "Make a copy of \`$ROOT/usr/$dir'."
+     [[ -d "$ROOT/usr/$dir" ]] \
+-        && cp -ax -l "$ROOT/usr/$dir" "$ROOT/usr/${dir}.usrmove-new"
++        && cp -a "$ROOT/usr/$dir" "$ROOT/usr/${dir}.usrmove-new"
+     echo "Merge the copy with \`$ROOT/$dir'."
+     [[ -d "$ROOT/usr/${dir}.usrmove-new" ]] \
+         || mkdir -p "$ROOT/usr/${dir}.usrmove-new"
+-    cp -axT $CP_HARDLINK --backup --suffix=.usrmove~ "$ROOT/$dir" "$ROOT/usr/${dir}.usrmove-new"
++    cp -a $CP_HARDLINK "$ROOT/$dir" "$ROOT/usr/${dir}.usrmove-new"
+     echo "Clean up duplicates in \`$ROOT/usr/$dir'."
+     # delete all symlinks that have been backed up
+     find "$ROOT/usr/${dir}.usrmove-new" -type l -name '*.usrmove~' -delete || :
 diff --git a/modules.d/40network/net-lib.sh b/modules.d/40network/net-lib.sh
 index 16730e5..d4b125d 100755
 --- a/modules.d/40network/net-lib.sh
@@ -433,8 +433,21 @@ index 1111d09..0c73d6a 100755
          mount -t tmpfs -o mode=0755,noexec,nosuid,nodev,strictatime tmpfs /newrun >/dev/null
      else
          # the initramfs binaries are located in /run, so don't mount it with noexec
+diff --git a/modules.d/99base/module-setup.sh b/modules.d/99base/module-setup.sh
+index 3a2246b..3111f7b 100755
+--- a/modules.d/99base/module-setup.sh
++++ b/modules.d/99base/module-setup.sh
+@@ -17,7 +17,7 @@ install() {
+ 
+     inst_multiple mount mknod mkdir sleep chroot chown \
+         sed ls flock cp mv dmesg rm ln rmmod mkfifo umount readlink setsid \
+-        modprobe
++        modprobe realpath
+ 
+     inst_multiple -o findmnt less kmod
+ 
 diff --git a/test/TEST-12-RAID-DEG/test.sh b/test/TEST-12-RAID-DEG/test.sh
-index f8dc08d..bca0af6 100755
+index f8dc08d..80bda65 100755
 --- a/test/TEST-12-RAID-DEG/test.sh
 +++ b/test/TEST-12-RAID-DEG/test.sh
 @@ -11,8 +11,8 @@ KVERSION=${KVERSION-$(uname -r)}
@@ -443,13 +456,13 @@ index f8dc08d..bca0af6 100755
      echo "CLIENT TEST START: $@"
 -    cp --sparse=always --reflink=auto $TESTDIR/disk2.img $TESTDIR/disk2.img.new
 -    cp --sparse=always --reflink=auto $TESTDIR/disk3.img $TESTDIR/disk3.img.new
-+    cp --sparse=always  $TESTDIR/disk2.img $TESTDIR/disk2.img.new
-+    cp --sparse=always  $TESTDIR/disk3.img $TESTDIR/disk3.img.new
++    cp --sparse=always $TESTDIR/disk2.img $TESTDIR/disk2.img.new
++    cp --sparse=always $TESTDIR/disk3.img $TESTDIR/disk3.img.new
  
      $testdir/run-qemu \
          -drive format=raw,index=0,media=disk,file=$TESTDIR/marker.img \
 diff --git a/test/TEST-99-RPM/test.sh b/test/TEST-99-RPM/test.sh
-index af64c24..1d51c4c 100755
+index af64c24..c827acb 100755
 --- a/test/TEST-99-RPM/test.sh
 +++ b/test/TEST-99-RPM/test.sh
 @@ -26,7 +26,7 @@ test_run() {
@@ -457,10 +470,36 @@ index af64c24..1d51c4c 100755
  
      mkdir -p "$rootdir/$TESTDIR"
 -    cp --reflink=auto -a \
-+    cp  -a \
++    cp -a \
         "$TESTDIR"/dracut-[0-9]*.$(uname -m).rpm \
         "$TESTDIR"/dracut-network-[0-9]*.$(uname -m).rpm \
         "$rootdir/$TESTDIR/"
 -- 
-2.28.0.rc2
+2.18.4
+
+From a2d718e91c978f020496d2b018940a71ed97aac0 Mon Sep 17 00:00:00 2001
+From: Ishimoto Shinobu <nagakamira@gmail.com>
+Date: Mon, 31 Aug 2020 17:05:54 +0900
+Subject: [PATCH] freebsd realpath
+
+Signed-off-by: Ishimoto Shinobu <nagakamira@gmail.com>
+---
+ dracut.sh | 2 +-
+ 1 file changed, 1 insertion(+), 1 deletion(-)
+
+diff --git a/dracut.sh b/dracut.sh
+index d8ddcb5..c2e9ad0 100755
+--- a/dracut.sh
++++ b/dracut.sh
+@@ -942,7 +942,7 @@ case "${drivers_dir}" in
+ 	;;
+ esac
+ 
+-readonly TMPDIR="$(realpath -e "$tmpdir")"
++readonly TMPDIR="$(realpath "$tmpdir")"
+ [ -d "$TMPDIR" ] || {
+     printf "%s\n" "dracut: Invalid tmpdir '$tmpdir'." >&2
+     exit 1
+-- 
+2.18.4
 
