fix logic
Signed-off-by: Ishimoto Shinobu <nagakamira@gmail.com>

diff --git a/scripts/check-updates b/scripts/check-updates
--- a/scripts/check-updates
+++ b/scripts/check-updates
@@ -11,20 +11,26 @@ unalias -a
 check_updates() {
 	mypkg="$1"
 
-	. $mypkg/Pkgfile
+	source $mypkg/Pkgfile
+
+	homepage="$(grep "^# URL[[:blank:]]*:" $mypkg/Pkgfile | sed 's/^# URL[[:blank:]]*:[[:blank:]]*//' | tr ' ' '\n' | awk '!a[$0]++')"
+	distfiles="${source[@]}"
 
 	local i p url sfname lpname bbname githubname rx found_version consider
 	local update_override=$mypkg/update
-	local original_name=$name
+	local original_pkgname=$name
+	local urlpfx urlsfx
 
 	if [ -r $update_override ]; then
 		. $update_override
 	fi
 
-	export LC_ALL=C
+	if ! type curl >/dev/null 2>&1; then
+		echo "ERROR: cannot find \`curl' executable!"
+		return 1
+	fi
 
-	homepage="$(grep "^# URL[[:blank:]]*:" $mypkg/Pkgfile | sed 's/^# URL[[:blank:]]*:[[:blank:]]*//' | tr ' ' '\n' | awk '!a[$0]++')"
-	distfiles="${source[@]}"
+	export LC_ALL=C
 
 	if [ -z "$site" ]; then
 		printf '%s\n' "$homepage"
@@ -35,26 +41,56 @@ check_updates() {
 		printf '%s\n' "$site"
 	fi |
 	while IFS= read -r url; do
-        	rx=
-        	urlpfx="${url}"
-        	urlsfx=
-        	case "$url" in
-			*download.kde.org/stable/applications/*|*download.kde.org/stable/frameworks/*|*download.kde.org/stable/plasma/*|\
-			*download.kde.org/stable/kdevelop/*|*download.kde.org/stable/krita/*|*download.kde.org/stable/clazy/*|\
-			*download.kde.org/stable/digikam/*|*download.kde.org/stable/phonon/*)
-			urlpfx="${url%%${version%.*}*}"
-			urlsfx="${url##${urlpfx}${version%.*}}"
-			urlsfx="${urlsfx#.*/}"
-			urlsfx="/${urlsfx#/}"
-			rx='href="\K[\d\.]+(?=/")'
-			;;
+		printf '%s\n' "$url"
+		if [ "$single_directory" ]; then
+			continue
+		fi
+		rx=
+		urlpfx="${url}"
+		urlsfx=
+		dirpfx=
+		case "$url" in
+			  *sourceforge.net/sourceforge*|\
+			  *code.google.com*|*googlecode*|\
+			  *launchpad.net*|\
+			  *cpan.*|\
+			  *pythonhosted.org*|\
+			  *github.com*|\
+			  *gitlab.com*|*gitlab.gnome.org*|*gitlab.freedesktop.org*|\
+			  *bitbucket.org*|\
+			  *ftp.gnome.org*|\
+			  *kernel.org/pub/linux/kernel/*|\
+			  *cran.r-project.org/src/contrib*|\
+			  *rubygems.org*)
+				continue
+				;;
+			*)
+				vdpfx=${vdprefix:-"|v|\\Q$name\\E"}
+				vdsfx=${vdsuffix:-"|\\.x"}
+				match=$(grep -Po "^[^/]+//[^/]+(/.+)?/($vdpfx)(?=[-_.0-9]*[0-9](?<!\\Q$name\\E)($vdsfx)/)" <<< "$url")
+				if [ "$?" = 0 ]; then
+					urlpfx="${match%/*}/"
+					dirpfx="${match##*/}"
+					urlsfx="${url#$urlpfx}"
+					urlsfx="${urlsfx#*/}"
+					rx="href=[\"']?(\\Q$urlpfx\\E)?\\.?/?\\K\\Q$dirpfx\\E[-_.0-9]*[0-9]($vdsfx)[\"'/]"
+				fi
+				;;
 		esac
-		if [ -z "$rx" ]; then
-			printf '%s\n' "$url"
-		else
-		curl --max-time 10 -Lsk "$urlpfx" |
-			grep -Po -i "$rx" | xargs -r -n 1 -I @@ printf '%s\n' "${urlpfx}@@${urlsfx}"
-        fi
+		if [ "$rx" ]; then
+			skipdirs=
+			curl --max-time 10 -Lsk "$urlpfx" |
+				grep -Po -i "$rx" | sort -Vru |
+				while IFS= read -r newver; do
+					newurl="${urlpfx}${newver}${urlsfx}"
+					if [ "$newurl" = "$url" ]; then
+						skipdirs=yes
+					fi
+					if [ -z "$skipdirs" ]; then
+						printf '%s\n' "$newurl"
+					fi
+				done
+		fi
 	done |
 	while IFS= read -r url; do
 		rx=
@@ -69,9 +105,10 @@ check_updates() {
 				lpname="$(printf %s "$url" | cut -d/ -f4)"
 				url="https://launchpad.net/$lpname/+download";;
 			*cpan.*)
-				name=${name#perl-};;
+				pkgname=${pkgname#perl-};;
 			*pythonhosted.org*)
-				name=${name#python-}
+				pkgname=${pkgname#python-}
+				pkgname=${pkgname#python3-}
 				url="https://pypi.org/simple/$name";;
 			*github.com*)
 				githubname="$(printf %s "$url" | cut -d/ -f4,5)"
@@ -85,28 +122,29 @@ check_updates() {
 				bbname="$(printf %s "$url" | cut -d/ -f4,5)"
 				url="https://bitbucket.org/$bbname/downloads"
 				rx='/(get|downloads)/(v?|\Q'"$name"'\E-)?\K[\d\.]+(?=\.tar)';;
-			*kernel.org/pub/linux/kernel/*)
-				rx=linux-'\K'${version%.*}'[\d.]+(?=\.tar\.xz)';;
-			*cran.r-project.org/src/contrib*)
-				rx='\b\Q'"${name#R-cran-}"'\E_\K\d+(\.\d+)*(-\d+)?(?=\.tar)';;
-			*rubygems.org*)
-				url="https://rubygems.org/gems/${name#ruby-}"
-				rx='href="/gems/'${name#ruby-}'/versions/\K[\d\.]*(?=")' ;;
 			*ftp.gnome.org*)
 				: ${pattern="\Q$name\E-\K[0-9]+\.[0-9]*[02468]\.[0-9.]*[0-9](?=)"}
 				url="http://ftp.gnome.org/pub/GNOME/sources/$name/cache.json";;
+			*kernel.org/pub/linux/kernel/*)
+				rx=linux-'\K'${version%.*}'[\d.]+(?=\.tar\.xz)';;
+			*cran.r-project.org/src/contrib*)
+				rx='\b\Q'"${pkgname#R-cran-}"'\E_\K\d+(\.\d+)*(-\d+)?(?=\.tar)';;
+			*rubygems.org*)
+				url="https://rubygems.org/gems/${pkgname#ruby-}"
+				rx='href="/gems/'${pkgname#ruby-}'/versions/\K[\d\.]*(?=")' ;;
+			*crates.io*)
+				url="https://crates.io/api/v1/crates/${pkgname#rust-}"
+				rx='/crates/'${pkgname#rust-}'/\K[0-9.]*(?=/download)' ;;
 			esac
 		fi
 
 		rx=${pattern:-$rx}
 		rx=${rx:-'(?<!-)\b\Q'"$name"'\E[-_]?((src|source)[-_])?\K([^-/_\s]*?\d[^-/_\s]*?)(?=(?:[-_.](?:src|source|orig))?\.(?:[jt]ar|shar|t[bglx]z|tbz2|zip))\b'}
-
 		curl -H 'Accept: text/html,application/xhtml+xml,application/xml,text/plain,application/rss+xml' --max-time 10 -Lsk "$url" |
 			grep -Po -i "$rx"
 	done |
 	tr _ . |
-	sort -Vu -r |
-	head -n 1 |
+	sort -Vu |
 	while IFS= read -r found_version; do
 		consider=true
 		p="$ignore "
@@ -126,6 +164,6 @@ check_updates() {
 	done
 }
 
-check_updates $1
+check_updates $1 | tail -1
 
 exit 0
