upgrade and i will remove gcc temperary if it not build

diff --git a/KEEP/rcS b/KEEP/rcS
--- a/KEEP/rcS
+++ b/KEEP/rcS
@@ -7,6 +7,11 @@ dmesg -n 1
 echo Mounting virtual filesystems...
 mount -t proc none /proc
 mount -t sysfs none /sys
+mount -t tmpfs /tmp /tmp
+mkdir /dev/pts
+mkdir /dev/shm
+mount -t devpts none /dev/pts
+mount -t tmpfs none /dev/shm
 
 echo Starting mdev hotplug...
 echo /sbin/mdev > /proc/sys/kernel/hotplug
@@ -16,11 +21,25 @@ echo Mounting root read-only...
 mount -o remount,ro /
 
 echo Checking filesystems...
-fsck -ATa
-if [ $? -eq 1 ]; then
-	echo Filesystem errors exist, fix manually.
-	sh
-	halt -r
+fsck -A -T -C -a
+if [ $? -gt 1 ]; then
+	echo
+	echo "***************  FILESYSTEM CHECK FAILED  ******************"
+	echo "*                                                          *"
+	echo "*  Please repair manually and reboot. Note that the root   *"
+	echo "*  file system is currently mounted read-only. To remount  *"
+	echo "*  it read-write type: mount -n -o remount,rw /            *"
+	echo "*  When you exit the maintainance shell the system will    *"
+	echo "*  reboot automatically.                                   *"
+	echo "*                                                          *"
+	echo "************************************************************"
+	echo
+	sulogin -p
+	echo "Automatic reboot in progress..."
+	umount -a -r
+	mount -o remount,ro /
+	reboot -f
+	exit 0
 fi
 
 echo Remounting root as read-write...
